In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
### Vocabulary size
voc_size=10000

In [4]:
#One Hot Representation
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[269, 7864, 2945, 4631], [269, 7864, 2945, 64], [269, 374, 2945, 2261], [1617, 7727, 1308, 7133, 9713], [1617, 7727, 1308, 7133, 6793], [6866, 269, 6594, 2945, 1537], [2876, 651, 665, 7133]]


### Word Embedding Represntation

In [5]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [6]:
import numpy as np

In [7]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  269 7864 2945 4631]
 [   0    0    0    0  269 7864 2945   64]
 [   0    0    0    0  269  374 2945 2261]
 [   0    0    0 1617 7727 1308 7133 9713]
 [   0    0    0 1617 7727 1308 7133 6793]
 [   0    0    0 6866  269 6594 2945 1537]
 [   0    0    0    0 2876  651  665 7133]]


In [8]:
dim=10
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [9]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [10]:
print(model.predict(embedded_docs))

[[[ 0.01622031  0.04801155  0.04248727 -0.02849324  0.00516726
   -0.03157952  0.03656336  0.02326605  0.04208722  0.02627876]
  [ 0.01622031  0.04801155  0.04248727 -0.02849324  0.00516726
   -0.03157952  0.03656336  0.02326605  0.04208722  0.02627876]
  [ 0.01622031  0.04801155  0.04248727 -0.02849324  0.00516726
   -0.03157952  0.03656336  0.02326605  0.04208722  0.02627876]
  [ 0.01622031  0.04801155  0.04248727 -0.02849324  0.00516726
   -0.03157952  0.03656336  0.02326605  0.04208722  0.02627876]
  [-0.01159748  0.01303988  0.04622762 -0.04389714  0.02734866
   -0.0179008   0.02804733  0.04832384  0.0470145   0.00612048]
  [ 0.03609053  0.0302257   0.02152033  0.01903901  0.02381188
   -0.04610454  0.0373064   0.04613082  0.03092351 -0.00118957]
  [-0.00088143 -0.021401   -0.01241404  0.01734246  0.0492945
    0.0035757   0.03389467 -0.02568332 -0.04192436 -0.03073202]
  [ 0.04158408 -0.02456658  0.0048326   0.00162041 -0.00337114
    0.01941773 -0.02807775  0.00070399  0.0371046

In [11]:
embedded_docs[0]

array([   0,    0,    0,    0,  269, 7864, 2945, 4631])

In [12]:
print(model.predict(embedded_docs)[0])  #10 dim of length 8

[[ 0.01622031  0.04801155  0.04248727 -0.02849324  0.00516726 -0.03157952
   0.03656336  0.02326605  0.04208722  0.02627876]
 [ 0.01622031  0.04801155  0.04248727 -0.02849324  0.00516726 -0.03157952
   0.03656336  0.02326605  0.04208722  0.02627876]
 [ 0.01622031  0.04801155  0.04248727 -0.02849324  0.00516726 -0.03157952
   0.03656336  0.02326605  0.04208722  0.02627876]
 [ 0.01622031  0.04801155  0.04248727 -0.02849324  0.00516726 -0.03157952
   0.03656336  0.02326605  0.04208722  0.02627876]
 [-0.01159748  0.01303988  0.04622762 -0.04389714  0.02734866 -0.0179008
   0.02804733  0.04832384  0.0470145   0.00612048]
 [ 0.03609053  0.0302257   0.02152033  0.01903901  0.02381188 -0.04610454
   0.0373064   0.04613082  0.03092351 -0.00118957]
 [-0.00088143 -0.021401   -0.01241404  0.01734246  0.0492945   0.0035757
   0.03389467 -0.02568332 -0.04192436 -0.03073202]
 [ 0.04158408 -0.02456658  0.0048326   0.00162041 -0.00337114  0.01941773
  -0.02807775  0.00070399  0.03710467 -0.04613737]]
